### ISSUE TITLE
Releasing for Brackets

### ISSUE THREAD

**Issue by cfjedimaster** [guardian/html-janitor#15]
I hate opening an issue for this as it is more of a comment. Please close as soon as soon as you want. I'm going to release a Brackets extension for this so folks can run it within - well - Brackets obviously. ;) I'll post a comment here when done.

**Comment by rrees** [comment]
@cfjedimaster sounds great! Let us know how it goes.

**Comment by cfjedimaster** [comment]
Per my other comment, this doesn't make sense now. (Feel free to re-open if I'm wrong. :)
