### ISSUE TITLE
More explanations

### ISSUE THREAD

**Issue by cfjedimaster** [guardian/html-janitor#16]
So - I thought I had an idea of what this library does, but after playing with the example, I'm really at a loss. Can you explain more what this library does - perhaps in the readme.md so others see it as well?

**Comment by homerjam** [comment]
+1

**Comment by rrees** [comment]
I have updated the README, can you tell me whether it is now clearer.

**Comment by cfjedimaster** [comment]
Yes. So in a way, it is a bit like AntiSammy? Is it smart enough to say, "tag so and so is ok but not attribute so and so"?

**Comment by rrees** [comment]
No it doesn't have any smarts the user must configure the whitelist.

We use it to create a subset of markup we wish to support in our content model.

**Comment by cfjedimaster** [comment]
Fair enough. I think you an close this now. I don't think this makes sense for Brackets now. (To be clear, I still think this is a cool library, but I don't see how it would be useful as an extension for an editor. :)
