### ISSUE TITLE
v1.0.1 incorrect

### ISSUE THREAD

**Issue by ankit** [guardian/html-janitor#20]
looks like the release for 1.0.1 was wrongly tagged https://github.com/guardian/html-janitor/releases

**Comment by rrees** [comment]
Yes indeed. Teaches me to use an automated script!

**Comment by rrees** [comment]
Okay that looks like its correct now. The bower version was correct so I'm not sure what happened with the tagging.

**Comment by ankit** [comment]
thanks for fixing it!
