### ISSUE TITLE
Fine-grained control over attribute values

### ISSUE THREAD

**Issue by bigdave** [guardian/html-janitor#26]
One problem we need solved is fine-grained control over attribute values, such that class="foo" is allowed and valid, but class="foo bar" would remove 'bar'.  Similar functionality would be desired for the style attribute.

Is this something you'd be interested in adding to html-janitor? We'd like to look into doing this if you're interested in having it added.

**Comment by bradvogel** [comment]
This might help: https://github.com/guardian/html-janitor/pull/27. It allows you to pass a function to determine if the attribute should be allowed.
